# database init, supports mysql too
spring.sql.init.platform=mysql
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASS}
# SQL is written to be idempotent so this is safe
# spring.sql.init.mode=always
# was가 시작될 때마다 schema.sql, data.sql을 실행
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
