jdbc.initLocation=classpath:db/mysql/schema.sql
jdbc.dataLocation=classpath:db/mysql/data.sql

jpa.showSql=true

jdbc.driverClassName=com.mysql.cj.jdbc.Driver

jdbc.url=${MYSQL_URL}
jdbc.username=${MYSQL_USER}
jdbc.password=${MYSQL_PASS}

jpa.database=MYSQL